#!/bin/bash

# Dual GPU Fix Script - Force NVIDIA as Primary Display
# For systems with Intel integrated + NVIDIA discrete graphics

set -e

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

if [ "$EUID" -ne 0 ]; then 
    echo -e "${RED}Error: This script must be run as root${NC}"
    echo "Usage: sudo $0"
    exit 1
fi

echo -e "${BLUE}==================================${NC}"
echo -e "${BLUE}  Dual GPU Fix Script${NC}"
echo -e "${BLUE}  Intel + NVIDIA Configuration${NC}"
echo -e "${BLUE}==================================${NC}"
echo ""

echo "This script will configure your system to use NVIDIA as the primary display device."
echo ""
echo "Detected GPUs:"
lspci | grep VGA
echo ""

read -p "Continue? (y/N): " -n 1 -r
echo
if [[ ! $REPLY =~ ^[Yy]$ ]]; then
    echo "Fix cancelled"
    exit 0
fi

# Method 1: Configure X to use NVIDIA by BusID
echo -e "\n${BLUE}=== Creating X Configuration for NVIDIA ===${NC}"

# Get NVIDIA BusID
NVIDIA_BUSID=$(lspci | grep -i "vga.*nvidia" | cut -d' ' -f1 | sed 's/\./:/')
echo "NVIDIA BusID: $NVIDIA_BUSID"

# Convert to X format (e.g., 01:00.0 -> PCI:1:0:0)
BUSID_DEC=$(echo $NVIDIA_BUSID | awk -F: '{printf "PCI:%d:%d:%d", strtonum("0x"$1), strtonum("0x"$2), strtonum("0x"$3)}')
echo "X BusID format: $BUSID_DEC"

# Create xorg.conf
cat > /etc/X11/xorg.conf << EOF
# Dual GPU Configuration - Force NVIDIA as Primary
# Generated by dual-gpu-fix.sh

Section "ServerLayout"
    Identifier     "Layout0"
    Screen      0  "Screen0" 0 0
    InputDevice    "Keyboard0" "CoreKeyboard"
    InputDevice    "Mouse0" "CorePointer"
    Option         "Xinerama" "0"
EndSection

Section "Files"
EndSection

Section "InputDevice"
    Identifier     "Mouse0"
    Driver         "mouse"
    Option         "Protocol" "auto"
    Option         "Device" "/dev/psaux"
    Option         "Emulate3Buttons" "no"
    Option         "ZAxisMapping" "4 5"
EndSection

Section "InputDevice"
    Identifier     "Keyboard0"
    Driver         "kbd"
EndSection

Section "Monitor"
    Identifier     "Monitor0"
    VendorName     "Unknown"
    ModelName      "Unknown"
    Option         "DPMS"
EndSection

Section "Device"
    Identifier     "Device0"
    Driver         "nvidia"
    VendorName     "NVIDIA Corporation"
    BoardName      "GeForce GT 1030"
    BusID          "$BUSID_DEC"
    Option         "TripleBuffer" "True"
    Option         "AllowEmptyInitialConfiguration"
EndSection

Section "Screen"
    Identifier     "Screen0"
    Device         "Device0"
    Monitor        "Monitor0"
    DefaultDepth    24
    SubSection     "Display"
        Depth       24
    EndSubSection
EndSection
EOF

echo -e "${GREEN}Created /etc/X11/xorg.conf with NVIDIA as primary${NC}"

# Method 2: Blacklist Intel graphics (optional, aggressive)
echo -e "\n${BLUE}=== Intel Graphics Options ===${NC}"
echo "You have Intel integrated graphics + NVIDIA discrete GPU."
echo ""
echo "Option A (Recommended): Keep Intel active, use NVIDIA for display"
echo "Option B (Aggressive): Disable Intel completely (NVIDIA only)"
echo ""
read -p "Disable Intel graphics? (y/N): " -n 1 -r
echo

if [[ $REPLY =~ ^[Yy]$ ]]; then
    cat > /etc/modprobe.d/blacklist-intel.conf << EOF
# Blacklist Intel graphics to force NVIDIA
blacklist i915
blacklist intel_agp
EOF
    echo -e "${YELLOW}Intel graphics will be disabled on next boot${NC}"
    update-initramfs -u
else
    echo "Keeping Intel graphics active (recommended for laptops)"
fi

# Method 3: Update GRUB to prioritize NVIDIA
echo -e "\n${BLUE}=== Updating GRUB Configuration ===${NC}"

GRUB_FILE="/etc/default/grub"
if ! grep -q "nvidia-drm.modeset=1" "$GRUB_FILE"; then
    sed -i 's/GRUB_CMDLINE_LINUX_DEFAULT="/GRUB_CMDLINE_LINUX_DEFAULT="nvidia-drm.modeset=1 /' "$GRUB_FILE"
    echo -e "${GREEN}Added nvidia-drm.modeset=1 to GRUB${NC}"
    update-grub
else
    echo "GRUB already configured"
fi

# Method 4: Create a script to set NVIDIA as primary on boot
echo -e "\n${BLUE}=== Creating Display Setup Script ===${NC}"

cat > /usr/local/bin/nvidia-primary.sh << 'EOF'
#!/bin/bash
# Set NVIDIA as primary display on startup

# Wait for X to start
sleep 2

# Set NVIDIA as primary
xrandr --setprovideroutputsource modesetting NVIDIA-0
xrandr --auto

# Optional: Force all outputs through NVIDIA
# xrandr --output HDMI-1 --primary --auto
EOF

chmod +x /usr/local/bin/nvidia-primary.sh

# Create systemd service
cat > /etc/systemd/system/nvidia-primary.service << EOF
[Unit]
Description=Set NVIDIA as primary GPU
After=display-manager.service

[Service]
Type=oneshot
ExecStart=/usr/local/bin/nvidia-primary.sh
RemainAfterExit=yes

[Install]
WantedBy=graphical.target
EOF

systemctl daemon-reload
systemctl enable nvidia-primary.service

echo -e "${GREEN}Created startup script to set NVIDIA as primary${NC}"

# Summary
echo -e "\n${GREEN}==================================${NC}"
echo -e "${GREEN}Configuration Complete!${NC}"
echo -e "${GREEN}==================================${NC}"
echo ""
echo "Changes made:"
echo "  ✓ Created xorg.conf with NVIDIA BusID: $BUSID_DEC"
echo "  ✓ Updated GRUB configuration"
echo "  ✓ Created nvidia-primary startup script"
if [[ $REPLY =~ ^[Yy]$ ]]; then
    echo "  ✓ Disabled Intel graphics"
fi
echo ""
echo -e "${YELLOW}You must reboot for changes to take effect${NC}"
echo ""
echo "After reboot, verify with:"
echo "  glxinfo | grep 'OpenGL renderer'"
echo "  xrandr --listproviders"
echo ""

read -p "Reboot now? (y/N): " -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]; then
    reboot
else
    echo "Remember to reboot manually"
fi
